prior = struct(                                                         ...
    'diffusivity',      makedist('uniform','lower',1e-7,'upper',2e-6),...
    'accumulationRate', makedist('uniform','lower',0.01,'upper',0.04),    ... %m/yr
    'surfaceTemp',      makedist('uniform','lower',-80,'upper',-25),    ... %Should be pretty well constrained
    'Const',            .914,  ...
    'referenceTemp',    251,     ...
    'bottomTemp',       makedist('uniform','lower',-25,'upper',25),...
    'C1',               1,... %Concentration of ice
    'C2',               makedist('uniform','lower',0,'upper',2e-6), ...  %Concentration of 1
    'C3',               makedist('uniform','lower',0,'upper',4e-6),...
    'sig1',             makedist('uniform','lower',9e-6,'upper',9.4e-6),... %electrical conductivity pure ice (S/m)
    'sig2',             makedist('uniform','lower',2.7,'upper',3.7),... %Electrical conductivity component 1 (S/m/M)
    'sig3',             makedist('uniform','lower',0.36,'upper',0.5),...
    'E1',               makedist('uniform','lower',0.5,'upper',0.52),... %Activation energy eV
    'E2',               makedist('uniform','lower',0.16,'upper',0.24),...
    'E3',               makedist('uniform','lower',0.17,'upper',0.21),...
    'Rth',              makedist('uniform','lower',30,'upper',400),...
    'Rfr',              makedist('uniform','lower',5,'upper',25) ...
    );
    
